# Generated by Django 4.2.1 on 2023-06-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_tuteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tuteur',
        ),
    ]
