# Generated by Django 4.2.1 on 2023-08-04 07:53

from django.db import migrations


def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_classe = Permission.objects.get(codename='add_classe')
    change_classe = Permission.objects.get(codename='change_classe')
    delete_classe = Permission.objects.get(codename='delete_classe')
    view_classe = Permission.objects.get(codename='view_classe')

    add_eleve = Permission.objects.get(codename='add_eleve')
    change_eleve = Permission.objects.get(codename='change_eleve')
    delete_eleve = Permission.objects.get(codename='delete_eleve')
    view_eleve = Permission.objects.get(codename='view_eleve')

    add_annee = Permission.objects.get(codename='add_annee')
    change_annee = Permission.objects.get(codename='change_annee')
    delete_annee = Permission.objects.get(codename='delete_annee')
    view_annee = Permission.objects.get(codename='view_annee')

    add_trimestre = Permission.objects.get(codename='add_trimestre')
    change_trimestre = Permission.objects.get(codename='change_trimestre')
    delete_trimestre = Permission.objects.get(codename='delete_trimestre')
    view_trimestre = Permission.objects.get(codename='view_trimestre')

    add_aviscollege = Permission.objects.get(codename='add_aviscollege')
    change_aviscollege = Permission.objects.get(codename='change_aviscollege')
    delete_aviscollege = Permission.objects.get(codename='delete_aviscollege')
    view_aviscollege = Permission.objects.get(codename='view_aviscollege')

    add_absence = Permission.objects.get(codename='add_absence')
    change_absence = Permission.objects.get(codename='change_absence')
    delete_absence = Permission.objects.get(codename='delete_absence')
    view_absence = Permission.objects.get(codename='view_absence')

    add_discipline = Permission.objects.get(codename='add_discipline')
    change_discipline = Permission.objects.get(codename='change_discipline')
    delete_discipline = Permission.objects.get(codename='delete_discipline')
    view_discipline = Permission.objects.get(codename='view_discipline')
    admin_discipline = Permission.objects.get(codename='admin_discipline')

    add_projet = Permission.objects.get(codename='add_projet')
    change_projet = Permission.objects.get(codename='change_projet')
    delete_projet = Permission.objects.get(codename='delete_projet')
    view_projet = Permission.objects.get(codename='view_projet')

    add_stage = Permission.objects.get(codename='add_stage')
    change_stage = Permission.objects.get(codename='change_stage')
    delete_stage = Permission.objects.get(codename='delete_stage')
    view_stage = Permission.objects.get(codename='view_stage')

    add_competencesconnaissances = Permission.objects.get(codename='add_competencesconnaissances')
    change_competencesconnaissances = Permission.objects.get(codename='change_competencesconnaissances')
    delete_competencesconnaissances = Permission.objects.get(codename='delete_competencesconnaissances')
    view_competencesconnaissances = Permission.objects.get(codename='view_competencesconnaissances')

    admin_permissions = [
        view_stage,
        add_stage,
        change_stage,
        delete_stage,
        view_absence,
        add_absence,
        change_absence,
        delete_absence,
        view_annee,
        change_annee,
        add_annee,
        delete_annee,
        view_discipline,
        add_discipline,
        change_discipline,
        delete_discipline,
        view_classe,
        add_classe,
        change_classe,
        delete_classe,
        view_eleve,
        view_projet,
        add_projet,
        change_projet,
        delete_projet,
        view_competencesconnaissances,
        add_competencesconnaissances,
        change_competencesconnaissances,
        delete_competencesconnaissances,
        view_aviscollege,
        add_aviscollege,
        change_aviscollege,
        delete_aviscollege,
        view_trimestre,
        add_trimestre,
        change_trimestre,
        delete_trimestre,
        admin_discipline,
    ]

    admins = Group(name='admins')
    admins.save()

    admins.permissions.set(admin_permissions)

    prof_permissions = [
        view_stage,
        add_stage,
        change_stage,
        delete_stage,
        view_absence,
        add_absence,
        change_absence,
        delete_absence,
        view_annee,
        view_discipline,
        add_discipline,
        change_discipline,
        delete_discipline,
        view_classe,
        view_eleve,
        view_projet,
        add_projet,
        change_projet,
        delete_projet,
        view_competencesconnaissances,
        add_competencesconnaissances,
        change_competencesconnaissances,
        delete_competencesconnaissances,
        view_aviscollege,
        add_aviscollege,
        change_aviscollege,
        delete_aviscollege,
        view_trimestre,
    ]

    profs = Group(name='profs')
    profs.save()
    profs.permissions.set(prof_permissions)

    visiteur_permissions = [
        view_stage,
        view_absence,
        view_annee,
        view_discipline,
        view_classe,
        view_eleve,
        view_projet,
        view_competencesconnaissances,
        view_aviscollege,
        view_trimestre,
    ]

    visiteurs = Group(name='visiteurs')
    visiteurs.save()
    visiteurs.permissions.set(visiteur_permissions)

    for user in User.objects.all():
        if user.role == 'ADMIN':
            admins.user_set.add(user)
        if user.role == 'PROF':
            profs.user_set.add(user)
        if user.role == 'INFO':
            visiteurs.user_set.add(user)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_tuteur'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
