# Generated by Django 4.2.1 on 2023-05-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=30, verbose_name='Intitulé')),
                ('edition', models.BooleanField(default=False)),
                ('dateDebut', models.DateField(null=True)),
                ('dateFin', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbRetard', models.IntegerField(default=0)),
                ('nbAbsenceExc', models.IntegerField(default=0, verbose_name="Demi-journées d'absences excusées")),
                ('nbAbsenceNonExc', models.IntegerField(default=0, verbose_name="Demi-journées d'absences non-excusées")),
                ('nbAbsenceTot', models.IntegerField(default=0, verbose_name="Demi-journées d'absences")),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.eleve')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.trimestre')),
            ],
        ),
    ]
