# Generated by Django 4.2.1 on 2023-05-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0002_trimestre_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimestre',
            name='dateDebut',
            field=models.DateField(null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='dateFin',
            field=models.DateField(null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='edition',
            field=models.BooleanField(default=False, verbose_name="Ouvert à l'édition"),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='intitule',
            field=models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], editable=False, max_length=30, verbose_name='Intitulé'),
        ),
    ]
