# Generated by Django 4.2.1 on 2023-05-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0003_alter_trimestre_datedebut_alter_trimestre_datefin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('EL', 'Eleve'), ('HP', 'Hote Payant'), ('EX', 'Echange')], max_length=10),
        ),
    ]
