# Generated by Django 4.2.1 on 2023-05-21 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletins', '0004_alter_eleve_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='nbAbsenceExc',
            field=models.PositiveIntegerField(default=0, verbose_name="Demi-journées d'absences excusées"),
        ),
        migrations.AlterField(
            model_name='absence',
            name='nbAbsenceNonExc',
            field=models.PositiveIntegerField(default=0, verbose_name="Demi-journées d'absences non-excusées"),
        ),
        migrations.AlterField(
            model_name='absence',
            name='nbRetard',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=30)),
                ('descriptif', models.CharField(blank=True, max_length=300)),
                ('dateDebut', models.DateField(null=True)),
                ('dateFin', models.DateField(null=True)),
                ('relectureActive', models.BooleanField(default=False)),
                ('enseigneeA', models.ManyToManyField(to='bulletins.eleve', verbose_name='enseignée à :')),
                ('enseigneeDans', models.ManyToManyField(to='bulletins.classe', verbose_name='enseignée en :')),
                ('enseigneePar', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='enseignée par :')),
                ('reluPar', models.ManyToManyField(related_name='relecteurs', to=settings.AUTH_USER_MODEL, verbose_name='est relu par :')),
                ('trimestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.trimestre')),
            ],
        ),
    ]
