# Generated by Django 4.2.1 on 2023-05-21 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletins', '0005_alter_absence_nbabsenceexc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='reluPar',
        ),
        migrations.AddField(
            model_name='discipline',
            name='reluPar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relecteurs', to=settings.AUTH_USER_MODEL, verbose_name='est relu par :'),
        ),
    ]
