# Generated by Django 4.2.1 on 2023-05-22 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletins', '0006_remove_discipline_relupar_discipline_relupar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='dateDebut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='dateFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='enseigneeA',
            field=models.ManyToManyField(blank=True, to='bulletins.eleve', verbose_name='enseignée à :'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='enseigneeDans',
            field=models.ManyToManyField(blank=True, to='bulletins.classe', verbose_name='enseignée en :'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='relectureActive',
            field=models.BooleanField(default=False, verbose_name='ouverte à relecture'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='reluPar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relecteurs', to=settings.AUTH_USER_MODEL, verbose_name='est relu par :'),
        ),
    ]
