# Generated by Django 4.2.1 on 2023-05-22 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletins', '0007_alter_discipline_datedebut_alter_discipline_datefin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='descriptif',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='enseigneePar',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='enseignée par :'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='reluPar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relecteurs', to=settings.AUTH_USER_MODEL, verbose_name='est relu par : '),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='trimestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.trimestre'),
        ),
    ]
