# Generated by Django 4.2.1 on 2023-05-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0008_alter_discipline_descriptif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='descriptif_correction',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='titre_correction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='typeEnseignement',
            field=models.CharField(blank=True, choices=[('P', 'Enseignement de période'), ('A', "Enseignement d'Atelier"), ('HH', 'Enseignement en heures hebdomadaires')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='descriptif',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='intitule',
            field=models.CharField(max_length=50),
        ),
    ]
