# Generated by Django 4.2.1 on 2023-05-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0009_discipline_descriptif_correction_discipline_titre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(max_length=1000)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('attitude', models.CharField(blank=True, max_length=2, null=True)),
                ('engagement', models.CharField(blank=True, max_length=2, null=True)),
                ('resultat', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='volumeHoraire',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='dateDebut',
            field=models.DateField(blank=True, null=True, verbose_name='A débuté le : '),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='dateFin',
            field=models.DateField(blank=True, null=True, verbose_name="S'est terminée le : "),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='trimestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.trimestre'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='typeEnseignement',
            field=models.CharField(blank=True, choices=[('P', 'Enseignement de période'), ('A', "Enseignement d'Atelier"), ('HH', 'Enseignement en heures hebdomadaires'), ('P_HH', 'Enseignement en heures hebdomadaires et en période')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='CompetencesConnaissances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='CompetencesAppreciations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(choices=[('A', 'acquis'), ('D', 'non acquis'), ('B', 'globalement acquis'), ('C', 'partiellement acquis')], max_length=20)),
                ('appreciation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.appreciation')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.competencesconnaissances')),
            ],
            options={
                'unique_together': {('competence', 'appreciation')},
            },
        ),
        migrations.AddField(
            model_name='appreciation',
            name='competencesConnaissances',
            field=models.ManyToManyField(limit_choices_to={'discipline': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.discipline')}, through='bulletins.CompetencesAppreciations', to='bulletins.competencesconnaissances', verbose_name='appartient à '),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.discipline'),
        ),
    ]
