# Generated by Django 4.2.1 on 2023-05-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0010_appreciation_discipline_volumehoraire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencesconnaissances',
            name='intitule',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
