# Generated by Django 4.2.1 on 2023-05-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0011_alter_competencesconnaissances_intitule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreciation',
            name='commentaire_correction',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='eleve',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bulletins.eleve'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appreciation',
            name='commentaire',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
