# Generated by Django 4.2.1 on 2023-05-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0012_appreciation_commentaire_correction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciation',
            name='competencesConnaissances',
            field=models.ManyToManyField(through='bulletins.CompetencesAppreciations', to='bulletins.competencesconnaissances', verbose_name='appartient à '),
        ),
        migrations.CreateModel(
            name='ListBulletinScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleves', models.ManyToManyField(to='bulletins.eleve')),
                ('trimestres', models.ManyToManyField(to='bulletins.trimestre')),
            ],
        ),
    ]
