# Generated by Django 4.2.1 on 2023-05-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0013_alter_appreciation_competencesconnaissances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='utiliserCompetence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discipline',
            name='utiliserMoyenne',
            field=models.BooleanField(default=True),
        ),
    ]
