# Generated by Django 4.2.1 on 2023-05-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0014_discipline_moyenne_discipline_utilisercompetence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='effectifs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='effectifs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='notePlusBasse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='notePlusHaute',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='nbAbsenceTot',
            field=models.PositiveIntegerField(default=0, verbose_name="Demi-journées d'absences"),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.classe'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('EL', 'Eleve'), ('HP', 'Hote Payant'), ('EX', 'Echange')], default='EL', max_length=10),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='dateDebut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='dateFin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
    ]
