# Generated by Django 4.2.1 on 2023-06-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0016_alter_classe_effectifs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=9)),
                ('is_active', models.BooleanField(default=False, verbose_name='en cours')),
            ],
        ),
        migrations.AddField(
            model_name='trimestre',
            name='annee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletins.annee'),
        ),
    ]
