# Generated by Django 4.2.1 on 2023-06-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0017_annee_trimestre_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimestre',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.annee'),
        ),
    ]
