# Generated by Django 4.2.1 on 2023-06-15 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0018_alter_trimestre_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='annee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletins.annee'),
        ),
    ]
