# Generated by Django 4.2.1 on 2023-06-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0021_alter_trimestre_intitule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimestre',
            name='intitule',
            field=models.CharField(choices=[('1e Trimestre', 'Trimestre 1'), ('2e Trimestre', 'Trimestre 2'), ('3e Trimestre', 'Trimestre 3')], max_length=30, verbose_name='Intitulé'),
        ),
    ]
