# Generated by Django 4.2.1 on 2023-06-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0022_alter_trimestre_intitule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='classe',
        ),
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ManyToManyField(blank=True, to='bulletins.classe', verbose_name='En classe de :'),
        ),
    ]
