# Generated by Django 4.2.1 on 2023-06-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0024_remove_eleve_classe_eleve_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='classe',
        ),
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ManyToManyField(blank=True, null=True, to='bulletins.classe'),
        ),
    ]
