# Generated by Django 4.2.1 on 2023-06-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0025_remove_eleve_classe_eleve_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.ManyToManyField(blank=True, to='bulletins.classe'),
        ),
    ]
