# Generated by Django 4.2.1 on 2023-06-16 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletins', '0026_alter_eleve_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='tuteur',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
