# Generated by Django 4.2.1 on 2023-06-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0027_classe_tuteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('EL', 'Eleve'), ('HP', 'Hote Payant'), ('EXC', 'Echange')], default='EL', max_length=10),
        ),
    ]
