# Generated by Django 4.2.1 on 2023-06-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0028_alter_eleve_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='typeEnseignement',
            field=models.CharField(blank=True, choices=[('Enseignement de période', 'Enseignement de période'), ("Enseignement d'atelier", "Enseignement d'Atelier"), ('Enseignement en heures hebdomadaires', 'Enseignement en heures hebdomadaires'), ('Enseignement en heures hebdomadaires et en période', 'Enseignement en heures hebdomadaires et en période')], max_length=60, null=True),
        ),
    ]
