# Generated by Django 4.2.1 on 2023-06-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0029_alter_discipline_typeenseignement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listbulletinscolaire',
            name='eleves',
            field=models.ManyToManyField(blank=True, to='bulletins.eleve'),
        ),
    ]
