# Generated by Django 4.2.1 on 2023-06-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0030_alter_listbulletinscolaire_eleves'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='presentBulletin',
            field=models.BooleanField(default=True, verbose_name='intégrer au bulletin'),
        ),
    ]
