# Generated by Django 4.2.1 on 2023-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0031_discipline_presentbulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbulletinscolaire',
            name='bulletinAbsencesRetards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listbulletinscolaire',
            name='bulletinUtilisationCompetence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listbulletinscolaire',
            name='bulletinVersionProvisoire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listbulletinscolaire',
            name='signatureBulletin',
            field=models.BooleanField(default=False),
        ),
    ]
