# Generated by Django 4.2.1 on 2023-06-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0032_listbulletinscolaire_bulletinabsencesretards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='nbAppreciationsVides',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
