# Generated by Django 4.2.1 on 2023-06-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0033_discipline_nbappreciationsvides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='utiliserCompetence',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='utiliserMoyenne',
        ),
    ]
