# Generated by Django 4.2.1 on 2023-06-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0034_remove_discipline_utilisercompetence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.TextField(blank=True, max_length=1000, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.eleve')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.trimestre')),
            ],
            options={
                'unique_together': {('eleve', 'trimestre')},
            },
        ),
    ]
