# Generated by Django 4.2.1 on 2023-06-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0035_aviscollege'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencesconnaissances',
            name='intitule_correction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
