# Generated by Django 4.2.1 on 2023-07-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0036_competencesconnaissances_intitule_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='correctionsAValider',
            field=models.BooleanField(default=False, verbose_name='corrections à valider'),
        ),
    ]
