# Generated by Django 4.2.1 on 2023-07-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0037_discipline_correctionsavalider'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='nbCorrections',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
