# Generated by Django 4.2.1 on 2023-07-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0038_discipline_nbcorrections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='nbCorrections',
        ),
    ]
