# Generated by Django 4.2.1 on 2023-07-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0039_remove_discipline_nbcorrections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=5),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('EL', 'Élève'), ('HP', 'Hôte payant(e)'), ('EXC', 'Échange ling.')], default='ELEVE', max_length=10),
        ),
    ]
