# Generated by Django 4.2.1 on 2023-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0040_alter_eleve_genre_alter_eleve_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='voirProf',
            field=models.BooleanField(default=True, verbose_name='Afficher les professeurs'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='intitule',
            field=models.CharField(max_length=60),
        ),
    ]
