# Generated by Django 4.2.1 on 2023-07-20 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletins', '0041_discipline_voirprof_alter_discipline_intitule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='typeEnseignement',
            field=models.CharField(blank=True, choices=[('PR', 'Enseignement de période'), ('AT', "Enseignement d'atelier"), ('HH', 'Enseignement en heures hebdomadaires'), ('PRHH', 'Enseignement en heures hebdomadaires et en période')], max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStage', models.CharField(blank=True, choices=[('AGR', 'Stage agricole'), ('ENT', 'Stage en entreprise'), ('SOC', 'Stage en milieu social'), ('AUTRE', 'Autre')], max_length=60, null=True)),
                ('nbJours', models.PositiveIntegerField(blank=True, null=True)),
                ('lieuStage', models.CharField(blank=True, max_length=200, null=True)),
                ('maitreStage', models.CharField(max_length=60)),
                ('descriptif', models.CharField(blank=True, max_length=600, null=True)),
                ('descriptif_correction', models.CharField(blank=True, max_length=600, null=True)),
                ('appreciation', models.CharField(blank=True, max_length=600, null=True)),
                ('appreciation_correction', models.CharField(blank=True, max_length=600, null=True)),
                ('dateDebut', models.DateField(blank=True, null=True, verbose_name='A débuté le : ')),
                ('dateFin', models.DateField(blank=True, null=True, verbose_name="S'est terminé le : ")),
                ('presentBulletin', models.BooleanField(default=True, verbose_name='intégrer au bulletin')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.eleve')),
                ('relecteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relecteur', to=settings.AUTH_USER_MODEL)),
                ('trimestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.trimestre')),
                ('tuteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
