# Generated by Django 4.2.1 on 2023-07-20 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0042_alter_discipline_typeenseignement_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='relectureActive',
            field=models.BooleanField(default=False, verbose_name='ouvert à relecture'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='eleve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletins.eleve'),
        ),
    ]
