# Generated by Django 4.2.1 on 2023-07-21 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0043_stage_relectureactive_alter_stage_eleve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='classe',
        ),
        migrations.AlterField(
            model_name='stage',
            name='eleve',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bulletins.eleve'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='maitreStage',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.trimestre'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='typeStage',
            field=models.CharField(choices=[('AGR', 'Stage agricole'), ('ENT', 'Stage en entreprise'), ('SOC', 'Stage en milieu social'), ('AUTRE', 'Autre')], max_length=60),
        ),
    ]
