# Generated by Django 4.2.1 on 2023-07-21 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletins', '0044_remove_stage_classe_alter_stage_eleve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='relecteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reluPar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stage',
            name='tuteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuteurStage', to=settings.AUTH_USER_MODEL),
        ),
    ]
