# Generated by Django 4.2.1 on 2023-07-22 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletins', '0045_alter_stage_relecteur_alter_stage_tuteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeProjet', models.CharField(choices=[('TA', "Travail d'année"), ('AUTRE', 'Autre')], max_length=60)),
                ('titre', models.CharField(blank=True, max_length=60, null=True)),
                ('titre_correction', models.CharField(blank=True, max_length=60, null=True)),
                ('descriptif', models.CharField(blank=True, max_length=600, null=True)),
                ('descriptif_correction', models.CharField(blank=True, max_length=600, null=True)),
                ('appreciation', models.CharField(blank=True, max_length=600, null=True)),
                ('appreciation_correction', models.CharField(blank=True, max_length=600, null=True)),
                ('relectureActive', models.BooleanField(default=False, verbose_name='ouvert à relecture')),
                ('presentBulletin', models.BooleanField(default=True, verbose_name='intégrer au bulletin')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleveProjet', to='bulletins.eleve')),
                ('relecteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relecteurProjet', to=settings.AUTH_USER_MODEL)),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.trimestre')),
                ('tuteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuteurProjet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
