# Generated by Django 4.2.1 on 2023-07-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0046_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='active',
        ),
        migrations.AlterField(
            model_name='projet',
            name='appreciation',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='appreciation_correction',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='descriptif',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='descriptif_correction',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='appreciation',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='appreciation_correction',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='descriptif',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='descriptif_correction',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
