# Generated by Django 4.2.1 on 2023-07-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0047_remove_eleve_active_alter_projet_appreciation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='annee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletins.annee'),
        ),
    ]
