# Generated by Django 4.2.1 on 2023-07-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0048_alter_classe_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimestre',
            name='intitule',
            field=models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=30, verbose_name='Intitulé'),
        ),
    ]
