# Generated by Django 4.2.1 on 2023-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0050_alter_discipline_typeenseignement'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='intitule_court',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
