# Generated by Django 4.2.1 on 2023-08-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0052_alter_competencesappreciations_evaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='typeEnseignement',
            field=models.CharField(blank=True, choices=[('PR', 'Enseignement de période'), ('AT', "Enseignement d'atelier"), ('HH', 'Enseignement en heures hebdomadaires'), ('PRHH', 'Enseignement en heures hebdomadaires et en période'), ('HHAT', 'Enseignement en heures hebdomadaires et en atelier'), ('ST', 'Semaine thématique'), ('PRHHAT', 'Enseignement en période, en heures hebdomadaires et en atelier'), ('SPE', 'Enseignement de spécialité (première générale)')], max_length=60, null=True),
        ),
    ]
