# Generated by Django 4.2.1 on 2023-08-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0053_alter_discipline_typeenseignement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'permissions': [('admin_discipline', 'Peut administrer les disciplines')]},
        ),
    ]
