# Generated by Django 4.2.1 on 2023-08-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0054_alter_discipline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='correctionsAValider',
            field=models.BooleanField(default=False, verbose_name='corrections à valider'),
        ),
        migrations.AddField(
            model_name='stage',
            name='correctionsAValider',
            field=models.BooleanField(default=False, verbose_name='corrections à valider'),
        ),
    ]
