# Generated by Django 4.2.1 on 2023-08-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0055_projet_correctionsavalider_stage_correctionsavalider'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbulletinscolaire',
            name='bulletinNotice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projet',
            name='typeProjet',
            field=models.CharField(choices=[('TA', "Travail d'année"), ('AUTRE', 'Projet divers'), ('PERS', 'Projet personnel'), ('COLL', 'Projet collectif')], max_length=60),
        ),
    ]
