# Generated by Django 4.2.1 on 2023-08-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0056_listbulletinscolaire_bulletinnotice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbulletinscolaire',
            name='bulletinAvisCollege',
            field=models.BooleanField(default=False),
        ),
    ]
