# Generated by Django 4.2.1 on 2023-08-08 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0057_listbulletinscolaire_bulletinaviscollege'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bareme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=50, null=True)),
                ('intro', models.CharField(blank=True, max_length=1000, null=True)),
                ('attitude', models.CharField(blank=True, max_length=300, null=True)),
                ('attitudeA', models.CharField(blank=True, max_length=400, null=True)),
                ('attitudeB', models.CharField(blank=True, max_length=400, null=True)),
                ('attitudeC', models.CharField(blank=True, max_length=400, null=True)),
                ('attitudeD', models.CharField(blank=True, max_length=400, null=True)),
                ('engagement', models.CharField(blank=True, max_length=300, null=True)),
                ('engagementA', models.CharField(blank=True, max_length=400, null=True)),
                ('engagementB', models.CharField(blank=True, max_length=400, null=True)),
                ('engagementC', models.CharField(blank=True, max_length=400, null=True)),
                ('engagementD', models.CharField(blank=True, max_length=400, null=True)),
                ('resultat', models.CharField(blank=True, max_length=300, null=True)),
                ('resultatA', models.CharField(blank=True, max_length=400, null=True)),
                ('resultatB', models.CharField(blank=True, max_length=400, null=True)),
                ('resultatC', models.CharField(blank=True, max_length=400, null=True)),
                ('resultatD', models.CharField(blank=True, max_length=400, null=True)),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.trimestre')),
            ],
        ),
    ]
