# Generated by Django 4.2.1 on 2023-08-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0058_bareme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bareme',
            name='trimestre',
        ),
        migrations.AddField(
            model_name='bareme',
            name='intitule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
