# Generated by Django 4.2.1 on 2023-08-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0059_remove_bareme_trimestre_bareme_intitule'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbulletinscolaire',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.bareme'),
        ),
    ]
