# Generated by Django 4.2.1 on 2023-08-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0060_listbulletinscolaire_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiseEnPageBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, max_length=50, null=True)),
                ('taillePolice', models.DecimalField(decimal_places=1, default=8.0, max_digits=3)),
                ('police', models.CharField(choices=[('Helvetica', 'Helvetica'), ('Courier', 'Courier')], default='Helvetica', max_length=30)),
                ('couleurAppreciation', models.CharField(default='#cccccc', max_length=10)),
                ('couleurStageProjet', models.CharField(default='#cccccc', max_length=10)),
                ('couleurAvis', models.CharField(default='#cccccc', max_length=10)),
                ('couleurNotice', models.CharField(default='#cccccc', max_length=10)),
                ('hauteurPage1', models.DecimalField(decimal_places=1, default=24.0, max_digits=3)),
                ('largeurPage1', models.DecimalField(decimal_places=1, default=20.0, max_digits=3)),
                ('hauteurPage2', models.DecimalField(decimal_places=1, default=27.7, max_digits=3)),
                ('largeurPage2', models.DecimalField(decimal_places=1, default=20.0, max_digits=3)),
            ],
        ),
    ]
