# Generated by Django 4.2.1 on 2023-08-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0061_miseenpagebulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbulletinscolaire',
            name='miseEnPage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.miseenpagebulletin'),
        ),
    ]
