# Generated by Django 4.2.1 on 2023-08-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0062_listbulletinscolaire_miseenpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bareme',
            name='piedPage',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
