# Generated by Django 4.2.1 on 2023-08-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0063_bareme_piedpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bareme',
            name='attitude',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='attitudeA',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='attitudeB',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='attitudeC',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='attitudeD',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='engagement',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='engagementA',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='engagementB',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='engagementC',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='engagementD',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='intitule',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bareme',
            name='intro',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='piedPage',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='resultat',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='resultatA',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='resultatB',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='resultatC',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='resultatD',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='titre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
