# Generated by Django 4.2.1 on 2023-08-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0065_alter_bareme_attitude_alter_bareme_attitudea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miseenpagebulletin',
            name='largeurPage2',
        ),
        migrations.AlterField(
            model_name='listbulletinscolaire',
            name='bulletinVersionProvisoire',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='miseenpagebulletin',
            name='couleurAppreciation',
            field=models.CharField(default='#ebebeb', max_length=10),
        ),
        migrations.AlterField(
            model_name='miseenpagebulletin',
            name='couleurAvis',
            field=models.CharField(default='#ebebeb', max_length=10),
        ),
        migrations.AlterField(
            model_name='miseenpagebulletin',
            name='couleurNotice',
            field=models.CharField(default='#ebebeb', max_length=10),
        ),
        migrations.AlterField(
            model_name='miseenpagebulletin',
            name='couleurStageProjet',
            field=models.CharField(default='#ebebeb', max_length=10),
        ),
    ]
