# Generated by Django 4.2.1 on 2023-08-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0066_remove_miseenpagebulletin_largeurpage2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bareme',
            name='defaut',
            field=models.BooleanField(default=False, verbose_name='définie par défaut'),
        ),
    ]
