# Generated by Django 4.2.1 on 2023-08-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0069_alter_bareme_attitude_alter_bareme_attitudea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listbulletinscolaire',
            name='notice',
        ),
    ]
