# Generated by Django 4.2.1 on 2023-12-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0072_alter_competencesappreciations_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='typeStage',
            field=models.CharField(choices=[('AGR', 'Stage agricole'), ('ENT', 'Stage en entreprise'), ('SOC', 'Stage en milieu social'), ('LING', 'Échange linguistique'), ('AUTRE', 'Stage divers')], max_length=60),
        ),
    ]
