# Generated by Django 4.2.1 on 2023-12-18 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0073_alter_stage_typestage'),
    ]

    operations = [
        migrations.AddField(
            model_name='miseenpagebulletin',
            name='largeurDescriptif',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='miseenpagebulletin',
            name='largeurEvaluation',
            field=models.IntegerField(default=55, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='miseenpagebulletin',
            name='largeurIntitule',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
