# Generated by Django 4.2.1 on 2023-12-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0074_miseenpagebulletin_largeurdescriptif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='activerMoyenne',
            field=models.BooleanField(default=True, verbose_name='afficher la moyenne'),
        ),
    ]
