# Generated by Django 4.2.1 on 2023-12-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0075_discipline_activermoyenne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='nbJours',
        ),
        migrations.AddField(
            model_name='appreciation',
            name='remarque_correction',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='cycle',
            field=models.CharField(choices=[('PRI', 'Primaire'), ('COL', 'Collège'), ('LYC', 'Lycée')], default='COL', max_length=10),
        ),
        migrations.AddField(
            model_name='discipline',
            name='remarque_correction',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='remarque_correction',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='dureeStage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='remarque_correction',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('EL', 'Élève'), ('HP', 'Hôte payant(e)'), ('EXC', 'Échange ling.')], default='EL', max_length=10),
        ),
    ]
