# Generated by Django 4.2.1 on 2025-12-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0076_remove_stage_nbjours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miseenpagebulletin',
            name='signature_directeur_college',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature directeur collège'),
        ),
        migrations.AddField(
            model_name='miseenpagebulletin',
            name='signature_directeur_lycee',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature directeur lycée'),
        ),
        migrations.AlterField(
            model_name='competencesappreciations',
            name='evaluation',
            field=models.CharField(choices=[('-', 'Non évalué'), ('Acquis', 'Acquis'), ('Non acquis', 'Non acquis'), ('Partiellement acquis', 'Partiellement acquis'), ('Globalement Acquis', 'Globalement acquis')], default='Non évalué', max_length=20),
        ),
    ]
