# Generated by Django 4.2.1 on 2025-12-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0080_eleve_emails_bulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsettings',
            name='email_message',
            field=models.TextField(blank=True, default="Bonjour,\n\nVous trouverez ci-joint le bulletin scolaire de {prenom} {nom} pour {trimestres}.\n\nCordialement,\nL'équipe de l'École Mathias Grünewald", help_text="Message personnalisé qui accompagne l'envoi des bulletins. Vous pouvez utiliser {prenom}, {nom} et {trimestres} comme variables.", null=True, verbose_name="Message d'accompagnement des bulletins"),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='from_email',
            field=models.EmailField(blank=True, help_text='Adresse email utilisée comme expéditeur par défaut', max_length=255, null=True, verbose_name='Email expéditeur'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='host',
            field=models.CharField(blank=True, help_text='Ex: smtp.gmail.com', max_length=255, null=True, verbose_name='Serveur SMTP'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='password',
            field=models.CharField(blank=True, help_text='Mot de passe SMTP', max_length=255, null=True, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=587, help_text='Port SMTP (587 pour TLS, 465 pour SSL)', null=True, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='username',
            field=models.CharField(blank=True, help_text="Email ou nom d'utilisateur SMTP", max_length=255, null=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
