# Generated by Django 4.2.1 on 2025-12-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0081_add_email_message_to_smtp_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsettings',
            name='email_subject',
            field=models.CharField(blank=True, default='Bulletin scolaire - {prenom} {nom} - {trimestres}', help_text='Objet personnalisé pour les emails de bulletins. Vous pouvez utiliser {prenom}, {nom} et {trimestres} comme variables.', max_length=255, null=True, verbose_name='Objet des emails de bulletins'),
        ),
    ]
