# Generated by Django 4.2.1 on 2025-12-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0082_add_email_subject_to_smtp_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Définit l'ordre d'affichage des enseignements dans le bulletin (0 = premier, plus le nombre est élevé, plus l'enseignement apparaît tard)", verbose_name="Ordre d'affichage dans le bulletin"),
        ),
    ]
